### ISSUE TITLE
Official code implementation

### ISSUE THREAD

**Issue by AvivSham** [joannahong/Lip-to-Speech-Synthesis-in-the-Wild#1]
Hi all,
Do you plan to release lip2sppech implementation?

Cheers,

**Comment by joannahong** [comment]
The official code is now available in [here](https://github.com/ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild). Thank you!

**Comment by AvivSham** [comment]
one final question please, the pretrained ASR models are the ASR models used to report the WER for LRS2/3?

**Comment by ms-dot-k** [comment]
No, it is for training the Lip2Speech model. (output-level content supervision)
